### ISSUE TITLE
Pip Installation Error

### ISSUE THREAD

**Issue by kevinzakka** [deepmind/launchpad#21]
I can't for the life of me get launchpad to install on my linux machine. With a fresh environment and via `pip install "dm-launchpad[tensorflow]"`, I get the following error when trying to `import launchpad`:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zakka/miniconda/envs/test/lib/python3.8/site-packages/launchpad/__init__.py", line 36, in <module>
    from launchpad.nodes.courier.node import CourierHandle
  File "/home/zakka/miniconda/envs/test/lib/python3.8/site-packages/launchpad/nodes/courier/node.py", line 21, in <module>
    import courier
  File "/home/zakka/miniconda/envs/test/lib/python3.8/site-packages/courier/__init__.py", line 26, in <module>
    from courier.python.client import Client  # pytype: disable=import-error
  File "/home/zakka/miniconda/envs/test/lib/python3.8/site-packages/courier/python/client.py", line 30, in <module>
    from courier.python import py_client
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by qstanczyk** [comment]
Maybe [this](https://stackoverflow.com/questions/43333207/python-error-while-loading-shared-libraries-libpython3-4m-so-1-0-cannot-open) helps?

**Comment by kevinzakka** [comment]
Worked, thanks @qstanczyk
